### ISSUE TITLE
ROS2 Dashing

### ISSUE THREAD

**Issue by SeungRyeol** [linorobot/ros2me#1]
Hello. I'm using linorobot really usefully.

Do you have plans to support ROS2 Dashing?
It means that do you have plans to make linorobot available well in ROS2 Dashing?

regards,
Shin

**Comment by grassjelly** [comment]
Hi,

Thanks for your interest. Yes, it’s part of the plan. But before that, I’ll release a final version for linorobot before migrating to ROS2. Development work should start around June. Closing this for now.
