### ISSUE TITLE
22.04 / Humble

### ISSUE THREAD

**Issue by samuk** [linorobot/ros2me#2]
Do you intend to update this for Humble? 

https://github.com/Tiryoh/ros2_setup_scripts_ubuntu/blob/master/ros2-humble-ros-base-main.sh

**Comment by grassjelly** [comment]
I dont have a machine to test Humble yet. Are you able to test if I make it compatible?

**Comment by samuk** [comment]
I don't have a full robot yet, but I could certainly install it and look for any issues.

**Comment by JHPHELAN** [comment]
I just tried it with Ubuntu 22.04 on a Raspberry Pi 4 4GB.  The git clone of ros2me and ./install seemed to run fine but when finished echo $ROS_DISTRO was empty.

**Comment by grassjelly** [comment]
did you source .bashrc?

**Comment by JHPHELAN** [comment]
Ah, I did not.  So I did and it installed ok.  Thanks!
I am a rank amateur so did not realize to do that.  
I barely know enough to know how to git clone the ros2me repo.
I would offer to make a pull request and update the readme.md for us total newbies, 
but am not yet confident enough in git to do that.
Can "source ~/.bashrc" be made part of .install to avoid this oversight?

I, and I know many others, are extremely impressed and grateful for Linorobot - an extremely sophisticated platform yet with much flexibility that is, more than most, "plug and play".  Thank you!

My plan is to adapt Linorobot to the NASA/JPL Open Source Rover:
[https://opensourcerover.jpl.nasa.gov/](url)
and
[https://github.com/nasa-jpl/open-source-rover](url)
to take it from remote control to autonomous. 
The challenge will be to adapt to the rover's 6-wheel-drive, 4-wheel-steering configuration.
Not sure whether to call it "6wd", "6x4" or "rover"

Thanks again,
Jim

**Comment by grassjelly** [comment]
Glad that worked. That's a good idea - added a prompt here: https://github.com/linorobot/ros2me/blob/master/install#L90 but please feel free to send a PR on the README too.

That's a really cool project. Let me know if you need more help. Would love to see Linorobot power more robot form factors.
