### ISSUE TITLE
update ros2me README.md

### ISSUE THREAD

**Issue by JHPHELAN** [linorobot/ros2me#3]
README.md says:
18.04 Eloquent
20.04 Foxy
20.04 Humble
but based on install I think it should be:
18.04 Eloquent 
20.04 **Galactic**
2**2**,04 Humble

What is the function of .travis.yml?  It's not mentioned in README.md nor install

**Comment by grassjelly** [comment]
fixed here: https://github.com/linorobot/ros2me/commit/b1dfcb6fee00000e3354dad3df090de9e4e4523a . Thanks! Closing this for now
